In [30]:
import pandas as pd
import numpy as np
import pickle
from matplotlib import pyplot

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression

In [26]:
df = pd.read_csv("petals.csv")
df

sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [27]:
array = df.values
X = array[:,0:4]
y = array[:,4]
X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.20, random_state=42)

In [28]:
log_model = LogisticRegression(solver='liblinear', multi_class='ovr')
log_model.fit(X_train, Y_train)

predictions = log_model.predict(X_validation)

In [29]:
print(accuracy_score(Y_validation, predictions))

print(confusion_matrix(Y_validation, predictions))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [36]:
pickle.dump(log_model, open("simple-model.pkl", "wb"), protocol=3)

In [37]:
log_model = pickle.load(open("simple-model.pkl", "rb"))

log_model.predict([[5, 3, 2, 1]])

array(['Iris-setosa'], dtype=object)